### ISSUE TITLE
LogFunc has no access to RIO's env context

### ISSUE THREAD

**Issue by jkachmar** [commercialhaskell/rio#114]
Currently `LogFunc`'s logging function is expressed in terms of `CallStack -> LogSource -> LogLevel -> Utf8Builder -> IO ()`, which prevents it from accessing any contextual information in `env`.

While this works well for most logging methodologies, it means that if one wants to use a structured logger like `Katip` they can't use any of the `LogFunc` utilities.

It doesn't stop anyone from using `RIO` on its own, it just means that the instances that `Katip` requires would have to be defined for `RIO App`, and only the `Katip` logging functions could be used.

I haven't given too much thought to what an _actual_ solution could look like, I'm mostly curious if this is something that could be added.

**Comment by snoyberg** [comment]
Because of the way that `RIO` works, my intention had been that when defining a `LogFunc`, _if_ you needed access to a larger `App` environment, you'd do something like `myLogFunc w x y z = runRIO myApp $ ...`. There's no better way to do it that I see that doesn't involve diving into existentials, and it's not even clear what the type signature would look like at that point.

**Comment by jkachmar** [comment]
Sorry I've left this open for so long, this seems like a satisfactory answer. Closing 😄
