### ISSUE TITLE
Include some mutable containers

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/rio#151]
In particular, `Deque` and possibly `DLList` from [`Data.Mutable`](https://www.stackage.org/haddock/lts-13.9/mutable-containers-0.3.4/Data-Mutable.html#g:4). I have a specific need for a `Deque` (or as list single-ended queue) in a rewrite of a `Writer` monad in yesod-form.

CC @lehins @nh2, I think you may have some feedback.

**Comment by lehins** [comment]
I don't know how often people need a Deque or DLList for them to be included in such a standard library as RIO. One of the pros though for including `mutable-containers` as a dependency is that it contains a drop-in replacement for `URef`.

**Comment by snoyberg** [comment]
I'd actually thought about reversing the dependency: moving the definition into `rio` and have `mutable-containers` depend on `rio`. I'd like to avoid increasing the dependency footprint at all.

**Comment by lehins** [comment]
Oh, in that case, since `mutable-containers` depends on `mono-traversable`, `rio` will not bring too many extra dependencies with it. The pro still stands, but in the opposite direction: `mutable-containers` will be able to use `URef` from `rio` :)

One thing I can suggest, if you'll be bringing only one of the data structures but not the other, say `Deque` into rio, I would  instead of having such a general interface as `MutablePushBack`, `MutablePushFront`, etc. have simple functions: `pushBackDeque`, `pushFrontDeque`, etc. and just reuse those in the `mutable-containers`

**Comment by snoyberg** [comment]
I think that makes sense. Just to get it out there: the other possibility would be a `RIO.Deque` module which is imported qualified. But I think the naming you suggest fits better with existing mutable structures like `IORef` and `TVar`.

**Comment by lehins** [comment]
I think putting it in a separate `RIO.Deque` module is still a good idea, cause `RIO` haddock page already takes a while to load, and it's not one of those day-to-day kind of data structures. Qualified import would work too, I was just following the `STM` convention eg. `readTBQueue`, `readTQueue`, etc.

**Comment by lehins** [comment]
I had idea about the `Deque`, that could be useful: namely the ablity to freeze the underlying mutable vector into a vector. Of course it can be implemented with a foldlDeque, but using freeze will use a faster memcpy. Something along those lines:

```haskell
freezeDeque :: (PrimMonad m, VG.Vector v a) => Deque v (PrimState m) a -> m (v a)
freezeDeque (Deque var) = do
  DequeState v start size <- readMutVar var
  V.freeze $ V.slice start size v
```

**Comment by snoyberg** [comment]
It would need to be more complex than that, since the `Deque` is circular and may place values at, for example, indices `6, 7, 0, 1, 2`. But yes, some kind of freeze is possible.

Another design point: the input and output vector types don't necessarily need to be the same, though it may be nicer from a type inference standpoint. Thoughts?

**Comment by lehins** [comment]
I see what you mean, should have looked a the code a bit closer before suggesting a simple freeze. 

Here are my thoughts with regard to
> the input and output vector types don't necessarily need to be the same

Pros:
* User can convert to any vector while data being copied (good use case is when building up deque with unboxed and producing a storable vector in the end)
* Whenever resulting vector is of a different type, direct conversion with `freezeDeque`, will be faster and require less memory than doing `V.convert <$> freezeDeque deque`

Cons:
* Cannot be implemented using two (since it's circular) `unsafeCopy` followed by `unsafeFreeze`, so it will be a bit slower for the same in/out vector type
* Can already[1] be implemented by the user with `foldlDeque`
* Besides a Unboxed -> Storable conversion I don't see any good use case for producing a vector of different type

In the end, I don't think it will matter too much, but for freezing I'd go with the simplest approach for the user, which IMHO is just keeping the vector type the same. 

[1] I was trying to think of a way I would implement that conversion without using internals by the means of `foldlDeque` and realized that there is no function that can produce the size of `Deque`

So maybe adding 3 functions? :) See #154

**Comment by snoyberg** [comment]
Sounds good! We'll follow up on that PR.
