### ISSUE TITLE
StrictData language extension

### ISSUE THREAD

**Issue by ezoerner** [commercialhaskell/rio#243]
The README states

> Make data fields strict by default, unless you have a good reason to do otherwise.

but I don't see the `StrictData` language pragma in the recommended list. Is this an oversight?

**Comment by snoyberg** [comment]
I personally don't recommend it because it's a non-local change inverting the meaning of code. Looking at `data Foo = Foo { bar: Int }` I no longer know if `bar` is strict or lazy. I think `StrictData` is a better default, but prefer explicitness in the code. (Not everyone agrees with me on this of course.)
