### ISSUE TITLE
Capitalization bikeshedding!

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/rio#30]
Somewhat spun off from #12.

We have rio the library, RIO the data type, RIO the module hierarchy. Do we want all of those capitalization schemes? rio lower case for the library seems pretty obvious, and the other two _must_ begin with a capital letter. But do we choose `RIO` or `Rio`. Or perhaps they should be different? After all, the name of the library is not really based on the `RIO` data type any more, but is its own moniker.

I'll give some arguments in comments below, just framing the discussion here.

**Comment by snoyberg** [comment]
Argument for `RIO` to be upper case in the data type: it's simple `ReaderT` + `IO`, so the letters `R`, `I`, and `O` are already capitalized. Counterpoint: if `io` is _both_ lowercase, it works.

Total aside: this bikeshedding around capitalization was one of the reasons pushing me towards using the `jump` name for this library instead of `rio`, see #8.

**Comment by mgsloan** [comment]
Framing seems good!  I prefer camelcase for acronyms in general.  Example mentioned by Taylor Fausuk elsewhere was `XMLHTTPRequest`.  Gross!  So the only consistent rule that works in all cases is camelcase even for acronyms.

**Comment by tejon** [comment]
Tossing in a vote for `Rio`, though I won't be upset if it stays all-caps.

**Comment by mgsloan** [comment]
Should we put this up for a twitter vote?  What's the process for making a decision?  Concerned that if we let it languish, `RIO` will just become the defacto choice due to the cost of refactoring adopters.

It's *ok* but I will probably wince a little bit when I see it, at least until I get used to it.  Seems rather shouty and harder to type, among the reasons already given.

**Comment by snoyberg** [comment]
OK, I'll make a poll.

**Comment by snoyberg** [comment]
https://twitter.com/snoyberg/status/958807583334248448

**Comment by roman** [comment]
Should this ticket be closed with final decission, or we want other data points besides the Twitter poll?

**Comment by snoyberg** [comment]
I'll refer the question to @mgsloan, since I think he's the strongest proponent of renaming. For the record, here are the poll results

<img width="298" alt="screen shot 2018-02-03 at 7 51 30 pm" src="https://user-images.githubusercontent.com/49415/35769938-ad936046-091b-11e8-8af8-b0330448a13e.png">

**Comment by mgsloan** [comment]
Hmm, I think it's interesting that 51% or so are interested in change away from `RIO`.  I don't like mixing `RIO` and `Rio`, it should be one or the other.

I wish that twitter polls would randomize the order so that there isn't bias based on the order.

However, since there doesn't seem to be much majority interest in changing to `Rio` / `Rio`, I suppose it seems reasonable to close this and I will just live with holding down shift for a few extra keys.

I do think that if one were to write down consistent readable naming rules, it makes the most sense to camelcase abbreviations.  So, therefore `Rio` would be better if we ever want to write down such a rule.

**Comment by snoyberg** [comment]
OK, closing.
