### ISSUE TITLE
Add trace functions

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/rio#31]
Discussion started at: https://www.reddit.com/r/haskell/comments/7r4wie/rio_a_prelude_replacement/dsv76en/

Options are either a `RIO.Trace`/`RIO.Debug` module, or including the functions in `RIO` itself with a warning attached. classy-prelude does the latter, and it seems like a good move here.

_Side note_ Should we also have a warning associated with the `undefined` provided by the `RIO` module?

**Comment by naushadh** [comment]
re `undefined`: +1 for warning or deprecated pragma.

**Comment by mgsloan** [comment]
I would love to have trace functions exported from the rio prelude that come with a warning attached.

**Comment by adituv** [comment]
On principle, I'd rather have a `RIO.Trace` module that must be explicitly pulled in, as well as having a warning attached.  Because it shouldn't be used in general (except temporarily while debugging), I feel it should not be made convenient to use.  Also because it should never exist in finished code, I consider trace functions peripheral to the rest of a library or application.

As for warning on undefined: definitely.

**Comment by mgsloan** [comment]
Hmm, I think they should be as convenient as possible to use.  It adds development friction to need to add `import Debug.Trace` in every module that I need to trace in.  The warning is what discourages leaving the trace in.  It particularly adds friction that there is no good default trace thing like `(HasCallstack, Show a) => a -> a`

I also differ on the matter of whether tracing should be left in pure code.  I think it should be fine to have trace logging in pure code, particularly if it is set to some "Debug" log level.  However, to most haskellers the idea of making it acceptable to put logging in pure code is horrifying.  I don't get what the issue is though.  Perhaps too speculative for rio :)

Having some trace functions in the prelude though, I think would be *very* good.

**Comment by adituv** [comment]
I have no problem with debug logging at a debug log level even in pure code, but that's not what this trace does.  It can't be turned on or off without adding or removing the statements (well, or programmatically piping stderr to null), which is why I feel it shouldn't be in finished code, while a logger can be configured to not show extraneous information to an end-user.

I would much prefer tracelike functionality based on a logger for that reason, but loggers are currently a little more complicated to set up when you just want quick-and-dirty debugging.  Perhaps there could be a default global log function that trace can use, and whose loglevel (at the very least) can be configured?

**Comment by mgsloan** [comment]
Yep, that makes sense to me!  Might make sense to do as a separate package from `rio` and eventually include it if it's popular and successful

**Comment by snoyberg** [comment]
Another question is: which string type should we use for the input to these functions? It seems like reasonable choices are:

* String
* Text
* DisplayBuilder

**Comment by adituv** [comment]
Right so for most use-cases I can think of `Text` should be most suitable for the user as very often traces are static strings.  When they aren't, they often use a `show` method (but we have `tshow` so that's fine) or don't have many appends so `DisplayBuilder` would be unnecessary.  Plus it's meant for debugging only - performance is hardly essential.

However, `debugBelch` only accepts `String` arguments so we'd either have to convert to `String` again to use that or output directly to `stderr`, losing the logging console output on Windows for GUI apps.  If losing the logging console output is acceptable then I'd advocate `Text`; otherwise `String`.

**Comment by snoyberg** [comment]
Further support for `Text`: we'll also provide `traceShow`-style functions.

I'm not too worried about performance here either, so having to convert internally to `String` is fine by my count. I'd just like to be advocating towards a consistent API.

Argument in favor of `DisplayBuilder`: a common use case in my experience is concating together `Int`s (like for counters) with text-like values. The `Display` typeclass makes this kind of usage easy, but there's no straightforward way to do this with `trace`. Counterpoint: it's easy enough to get ugly output with `traceShow (someText, someInt, blah)`.

**Comment by adituv** [comment]
How about something like `traceDisplay` or `traceDisplayBuilder` etc?  I see no reason why not to include it as an option comparable to `traceShow`.

I've drafted an `RIO.Prelude.Trace` module here: https://github.com/commercialhaskell/rio/compare/commercialhaskell:2c387c8...adituv:7579597

Documentation and possibly reducing the exposed functionality still to do.

**Comment by snoyberg** [comment]
I think a shorter name than `traceDisplayBuilder` would be warranted. Actual naming may depend on what we end up calling the builder type (CC @chrisdone, relevant to #51).

**Comment by snoyberg** [comment]
This is on master now, closing.
