### ISSUE TITLE
putStrLn is missing

### ISSUE THREAD

**Issue by bonds** [commercialhaskell/rio#34]
I thought to try out RIO by creating a new project with ````stack new riotest````. I added the long list of language pragma to the project cabal file for both the library and executable subprojects. I added ````import RIO```` to app/Main.hs and src/Lib.hs. And then I tried to compile. And then I discovered there's no putStrLn. And then I pondered why.

I thought it could be because String is evil. But then why not putStrLn from Data.Text.IO? Could be naked IO is evil. I see there's a logging library in RIO, maybe I'm being encouraged to use that?

Anyhow, it was surprising to see the default template is broken when using RIO, and it was surprising that putStrLn wasn't included. I guess I'm somewhere between a beginner and intermediate Haskeller. I can get hello world going, but I only understand Monads every once in a while, and only for a few hours at a time. ;) Just offering that as context as you ponder what part of your potential audience to focus on at this point.

I imagine you'll address putStrLn in the docs at some point, or maybe when you add a stack template, app/Lib.hs will use Logger with a comment telling folks that putStrLn is lame and you should really be using a logging framework if you want to output stuff to the terminal. Or maybe I'm guessing wrong.

**Comment by tejon** [comment]
> Could be naked IO is evil. I see there's a logging library in RIO, maybe I'm being encouraged to use that?

This was my assumption when I discovered the absence of all the console output functions. Personally, I'm OK with it; `import System.IO` is not expensive, and it forces you to actually think when you're reaching for `putStrLn`. For prototyping it's fine, but there's usually a better long-term solution.

**Comment by snoyberg** [comment]
Have a look at #5, and also the [beware of readFile](https://www.snoyman.com/blog/2016/12/beware-of-readfile) blog post which deals with questions around character encoding for textual I/O functions. In other words, the reason we haven't added `putStrLn` yet is because it's unclear what the correct design point is.

For now, I'd recommend either using the built-in logging code, or importing `RIO.Text` qualified and using those functions.

I'm definitely open to resolving this situation better, input welcome. It may be better though to consolidate the discussion on #5.

**Comment by bonds** [comment]
Got it, thanks @snoyberg, I'll close this ticket so the conversation can continue on #5.
