### ISSUE TITLE
Remove partial functions from reexports

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/rio#43]
A number of modules we reexport provide partial functions. We should remove those, or at least put them in some kind of partial function modules.

**Comment by adituv** [comment]
I already started on this a while back and will continue on this after the weekend unless someone else particularly wants to.

https://github.com/adituv/rio/tree/hide-partials

**Comment by AnthonyJacob** [comment]
It would require more work, but instead of moving them into another `.Unsafe` module it would be better to remove their partiality and change their signature to ` ... -> Maybe result` or `... -> Either error result`.

Then you could provide partial functions `Dev.fromMaybe :: Maybe a -> a` and `Dev.fromEither` to make it clear, these functions should be used only during development.

**Comment by tejon** [comment]
I don't think Rio intends to change the signatures of any existing functions. I kind of like the idea of `RIO.Unsafe` for `unsafePerformIO` and its ilk, but partials like `read` and `head` which have total equivalents (`reads`, `listToMaybe`) should be done away with entirely.

That said, this might be handy:
```
skull :: b -> (a -> b) -> [a] -> b
skull d f = maybe d f . listToMaybe
```

**Comment by adituv** [comment]
@AnthonyJacob

While I agree you should be careful with partial functions, I also feel that a general-purpose library like this should still keep all functionality from libraries it reexports so that users don't have to also pull in the underlying packages to access certain things.  There are perfectly valid uses of partial functions, such as:

```
countUniques :: Ord a => [a] -> [(a, Int)]
countUniques = fmap (head &&& length) . group . sort

toUnixLineEnds :: Text -> Text
toUnixLineEnds = Text.replace "\r\n" "\n" -- Text.replace is partial in the first argument
```

Obviously you could wrap the partial functions in `Maybe` like you're suggesting and then just have a `fromJust` or something, but then you may as well just use the original partial functions as they are guaranteed total in these contexts, and the extra conversion would just be unnecessary noise.

I also disagree with your proposed "development-only" message because it's misleading, due to cases like the above.

Ultimately I'm in favour of exposing all reasonable partial functions from a `.Unsafe` module, though I am still hesitant to put e.g. `Text.replace` in there when functions like that are "barely partial"

**Comment by mgsloan** [comment]
It's hard due rule out /all/ partial functions, due to things like `div 1 0 :: Int` throwing `divide by zero`.  Perhaps even that could be cured though, by exporting a default `unsafeDiv` and also `safeDiv`.  Then have a compatibility module that exports `div = unsafeDiv`.

**Comment by adituv** [comment]
Why would `safeDiv` need that?  Is there some reason we can't just handle the cases directly, like

```
safeDiv :: Integral a => a -> a -> Maybe a
safeDiv _ 0 = Nothing
safeDiv x y = x `div` y
```

We have `Eq a` indirectly via `Integral a` already so I can't see why this wouldn't work.

**Comment by mgsloan** [comment]
Hmm, yeah perhaps that could work well.  If someone defined Integral for vector-like things then it would be broken, though.  But they would have needed to make up bogus definitions of `toRational` / `Enum` to do that anyway, so maybe it's no big deal.

**Comment by tejon** [comment]
> There are perfectly valid uses of partial functions, such as:

Fair point. And this sparks a new idea for bikeshed paint: `RIO.TrustMe`

(I wasn't aware of that behavior in `Text.replace` -- I wonder why an empty first argument doesn't simply return the unmodified input? Not saying the existing behavior is nonsensical, just seems like it would have been harmless to make it total.)

**Comment by adituv** [comment]
https://github.com/adituv/rio/blob/38d012082b9d59098352a25ca92c22a4f6577bf7/src/RIO/Text.hs#L156

So I've implemented wrappers for the empty text case for various "barely-partial" functions in Data.Text, but would like feedback on the direction to go for this before I continue.  Current options:

1. Put them in RIO.Text.Unsafe/RIO.Text.TrustMe/...
2. Add default values as if the "needle" is never found.  All functions that are partial like this are searching for text that must not be empty, so this seems like a viable option.
    1. Some other semantics for the empty case.  E.g. `replace "" str` could be `intercalate str . chunksOf 1` to more accurately match the behaviour given in Data.Text's documentation
3. Wrap the return type in `Maybe` and use `Nothing` for the empty case. 

My personal preference would be 2, but I am unsure whether the implemented semantics make sense in all cases, or even whether maintaining safe variants of lesser used functions is even within the intended scope of rio.

**Comment by snoyberg** [comment]
I think (1) is uncontroversial, and I'd recommend the name Partial for the
module. Unsafe implies the possibility of segfault, which isn't the case
here.

For the moment, I lean away from having versions of functions which keep
the same name as a partial function but change either the type or the
semantics. That can lead to confusion when moving from the base libraries
themselves. How about giving them new names instead?

**Comment by tejon** [comment]
+1 to `Partial`.

-0.5 to writing new functions for Rio. I think the guideline of sticking to re-exports of established libraries is worth sticking to in general, especially while the core is not yet stable. Much as I'd love that total `Text.replace`, the fact that we even need to discuss how it behaves makes me feel that it's premature to introduce it here.

**Comment by snoyberg** [comment]
@adituv Did you want to send a PR for this one? We're trying to get towards a first stable release, and the changes discussed here are on that roadmap (see #52).

**Comment by adituv** [comment]
Ah sorry I've been really busy with university work lately.  I should be able to get the PR in this evening though

**Comment by snoyberg** [comment]
Awesome, thank you!

**Comment by adituv** [comment]
Looking at this again, I'm not 100% sure how to deal with some of the functions in `Data.List` as many of them misbehave or do not terminate in the presence of an infinite list.  Should `foldl` and `scanr` be in `.Partial` because they can't be used with an infinite list argument?

Non-terminating examples that may be less obviously non-terminating:
```
λ> take 10 $ scanr1 (+) [1..]
λ> take 10 $ foldl (\xs x -> x:xs) [] [1..]
```

For now I'm going to leave them in the main module, but this is something I think we should address before the PR is merged.

**Comment by snoyberg** [comment]
I think they should not be considered partial. I _would_ see an interesting argument to be made about dropping `foldl` entirely (since `foldl'` is almost always the better choice), but I'm not sure about it.
