### ISSUE TITLE
Where should I ask question related to RIO?

### ISSUE THREAD

**Issue by Josef-Vonasek** [commercialhaskell/rio#48]
I would like to use RIO for my next project (nothing serious, I am Haskell beginner) and I expect I will hit some difficulties on my way (maybe trivial).

As an example I am trying to parse new file format. But first I need to reverse engineer its structure. Therefore I tried to load the whole file into Bytestring.Lazy (it is big) and split the file into ascii text and binary nonsense (which I have to figure out what is it for). So I tried using `dropWhile isAscii, takeWhile isAscii` but I need to be able to compare `Word` with `Char`. Sadly RIO does not export `fromEnum` nor `Bytestring.Char8` which would allow me to do this, so I ask myself if it is intentional or not, and whether my approach is even right.

I suspect Github issues are not the right place to ask. So I wonder if you use discourse or some similar chat app.

**Comment by snoyberg** [comment]
Since the project is just kicking off and not totally set up yet, we don't really have a great answer to this question (again, _yet_). And you're unfortunately more likely to end up running into these issues, again because it's not totally ready.

One possibility is asking on the Commercial Haskell mailing list (info at https://github.com/commercialhaskell/commercialhaskell#readme).

For your specific question: it seems like the `ord` and `chr` functions from `Data.Char` (and on master, reexported from `RIO.Char`), likely together with `fromIntegral`, would provide what you're looking for.

I think it's highly unlikely that we'll end up exporting the `.Char8` modules here, since they're often the source of bugs (like truncating unicode code points).

**Comment by snoyberg** [comment]
I don't think anything's left for this issue, so closing.
