### ISSUE TITLE
More informative documentation for RIO module

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/rio#61]
From a documentation perspective, it is quite hard for a user to tell what the `RIO` module exports.  This is because it uses `module` exports.  The re-export depth can be quite high.  For example, `RIO` exports `module RIO.Prelude.Reexports`, and it exports `module UnliftIO`, which itself consists of module exports.  From the perspective of the compiler or heavy ghci user that just uses `:bro RIO` (`:browse`), this doesn't obscure anything at all.  However, for a reader of the documentation, it can be hard to tell what `RIO` really provides.

I started improving the readability of the haddocks for `RIO.Prelude.Reexports` - https://gist.github.com/mgsloan/bec603328664ea7d20075fdddefad5a0 , but I started wondering if it would be better move it into the `RIO` module and switch everything over to explicit exports.  There are some downsides to this idea, though.  One of them is that it may be easy to add something and forget to add it to the re-exports.

So, it seems like the best option would be to improve haddock to allow some annotation on module re exports which causes them to be expanded.

Now, a fair question would be whether we really want that - the full docs for the RIO module might be overwhelming particularly with the large instance lists for many of the classes.  I think it'd be more helpful than harmful, though.  To me it makes sense to be able to read the full docs for your prelude in one page, and also be able to use browser text search within that page.

**Comment by adituv** [comment]
Honestly I am considering whether `RIO.Prelude.Reexports` should be removed entirely and its contents distributed across other modules.  Whether or not something is just reexported from another package isn't really that important for an end-user to know, and having to search multiple places in the documentation for a function definition because you don't know whether it's a reexport is not great.

If we went this route, I think an organisation similar to `base` would work well - reexports should go in modules like `RIO.Text` etc already do, and then the most useful ones could then be exported from `RIO` as well.  This would probably be quite a lot of work though.

As for improving haddock, it already expands exported module documentation for modules that are not exported, so for everything other than `UnliftIO` we could just add them to `other-modules`.

**Comment by mgsloan** [comment]
@adituv Agreed, Reexports is a bit weird, seems like it's mostly organization for development of RIO.  PR #72 hides export of those modules.  It's rather unorganized, though, and results in a funny mishmash of section headers:

![2018-03-20_395x667_scrot](https://user-images.githubusercontent.com/22570/37644752-03e4fba6-2be2-11e8-9d12-3955c8808925.png)

**Comment by lehins** [comment]
@snoyberg Do you think that #163 addressed this issue or there is more improvements need to be done to the documentation organization.

**Comment by snoyberg** [comment]
I think it addressed it, good catch. Closing.
